// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat/chat.proto

package chatgen

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChatMessage struct {
	From                 *User                  `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Message              string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_767a49518b351716, []int{0}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetFrom() *User {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *ChatMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChatMessage) GetTimestamp() *timestamppb.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_767a49518b351716, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserList struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserList) Reset()         { *m = UserList{} }
func (m *UserList) String() string { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()    {}
func (*UserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_767a49518b351716, []int{2}
}

func (m *UserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserList.Unmarshal(m, b)
}
func (m *UserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserList.Marshal(b, m, deterministic)
}
func (m *UserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserList.Merge(m, src)
}
func (m *UserList) XXX_Size() int {
	return xxx_messageInfo_UserList.Size(m)
}
func (m *UserList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserList.DiscardUnknown(m)
}

var xxx_messageInfo_UserList proto.InternalMessageInfo

func (m *UserList) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type JoinResponse struct {
	Error                int32    `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_767a49518b351716, []int{3}
}

func (m *JoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResponse.Unmarshal(m, b)
}
func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResponse.Marshal(b, m, deterministic)
}
func (m *JoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResponse.Merge(m, src)
}
func (m *JoinResponse) XXX_Size() int {
	return xxx_messageInfo_JoinResponse.Size(m)
}
func (m *JoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

func (m *JoinResponse) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *JoinResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_767a49518b351716, []int{4}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ChatMessage)(nil), "ChatMessage")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*UserList)(nil), "UserList")
	proto.RegisterType((*JoinResponse)(nil), "JoinResponse")
	proto.RegisterType((*Empty)(nil), "Empty")
}

func init() {
	proto.RegisterFile("chat/chat.proto", fileDescriptor_767a49518b351716)
}

var fileDescriptor_767a49518b351716 = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0xab, 0xd3, 0x40,
	0x14, 0xc5, 0x9b, 0x36, 0x69, 0x9b, 0xdb, 0xaa, 0x30, 0xb8, 0x88, 0x11, 0x6d, 0x19, 0x10, 0x8b,
	0xe0, 0x44, 0xeb, 0x46, 0x10, 0x5c, 0x28, 0x6e, 0x44, 0x37, 0xa9, 0x6e, 0xdc, 0xe5, 0xcf, 0xed,
	0x74, 0xc4, 0x99, 0x09, 0x33, 0x53, 0xe1, 0xc1, 0xfb, 0x66, 0xef, 0xcb, 0x3d, 0x32, 0x79, 0xd3,
	0xf6, 0x2d, 0xde, 0x26, 0xe4, 0x1c, 0x4e, 0xce, 0x2f, 0xf7, 0xce, 0xc0, 0x93, 0xe6, 0x50, 0xb9,
	0xa2, 0x7f, 0xb0, 0xce, 0x68, 0xa7, 0xf3, 0x15, 0xd7, 0x9a, 0xff, 0xc3, 0xc2, 0xab, 0xfa, 0xb8,
	0x2f, 0x9c, 0x90, 0x68, 0x5d, 0x25, 0xbb, 0x21, 0x40, 0xaf, 0x61, 0xf1, 0xf5, 0x50, 0xb9, 0x9f,
	0x68, 0x6d, 0xc5, 0x91, 0x3c, 0x83, 0x78, 0x6f, 0xb4, 0xcc, 0xa2, 0x75, 0xb4, 0x59, 0x6c, 0x13,
	0xf6, 0xdb, 0xa2, 0x29, 0xbd, 0x45, 0x32, 0x98, 0xc9, 0x21, 0x95, 0x8d, 0xd7, 0xd1, 0x26, 0x2d,
	0x83, 0x24, 0x1f, 0x21, 0x3d, 0xd5, 0x66, 0x13, 0xff, 0x65, 0xce, 0x06, 0x30, 0x0b, 0x60, 0xf6,
	0x2b, 0x24, 0xca, 0x73, 0x98, 0xbe, 0x81, 0xb8, 0x27, 0x90, 0xc7, 0x30, 0x16, 0xad, 0x87, 0xa6,
	0xe5, 0x58, 0xb4, 0x84, 0x40, 0xac, 0x2a, 0x19, 0x40, 0xfe, 0x9d, 0xbe, 0x86, 0x79, 0x9f, 0xfd,
	0x21, 0xac, 0x23, 0xcf, 0x21, 0x39, 0x5a, 0x34, 0x36, 0x8b, 0xd6, 0x93, 0xf3, 0x7f, 0x0e, 0x1e,
	0xfd, 0x0c, 0xcb, 0xef, 0x5a, 0xa8, 0x12, 0x6d, 0xa7, 0x95, 0x45, 0xf2, 0x14, 0x12, 0x34, 0x46,
	0x1b, 0xdf, 0x9f, 0x94, 0x83, 0x78, 0x78, 0x1c, 0x3a, 0x83, 0xe4, 0x9b, 0xec, 0xdc, 0xd5, 0xf6,
	0x26, 0x1a, 0x96, 0xb3, 0x43, 0xf3, 0x5f, 0x34, 0x48, 0x5e, 0x42, 0xfc, 0x57, 0x0b, 0x45, 0x06,
	0x5c, 0xfe, 0x88, 0x5d, 0x62, 0xe8, 0x88, 0xbc, 0x82, 0x85, 0x45, 0xd5, 0x86, 0x5d, 0x2e, 0xd9,
	0xc5, 0x66, 0xf3, 0x29, 0xf3, 0xa5, 0x74, 0x44, 0x56, 0x30, 0xe7, 0xe8, 0xfa, 0x0a, 0x4b, 0xee,
	0xdc, 0x3c, 0x65, 0x61, 0x36, 0xdf, 0x03, 0xba, 0x43, 0xb5, 0x73, 0x06, 0x2b, 0x19, 0x68, 0xf7,
	0xda, 0xe8, 0xe8, 0x5d, 0x44, 0x5e, 0x00, 0xb4, 0xc2, 0x36, 0x5a, 0x29, 0x6c, 0x5c, 0x88, 0x9d,
	0x30, 0x5f, 0xde, 0xff, 0x29, 0xb8, 0x70, 0x87, 0x63, 0xcd, 0x1a, 0x2d, 0x0b, 0xa3, 0x6b, 0xa9,
	0x95, 0xc3, 0x82, 0x9b, 0xae, 0x79, 0xeb, 0xaf, 0x89, 0x3f, 0x9a, 0x82, 0xa3, 0xfa, 0xd4, 0x4b,
	0x8e, 0xaa, 0x9e, 0x7a, 0xeb, 0xc3, 0x6d, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4b, 0xb0, 0x48, 0xa2,
	0x47, 0x02, 0x00, 0x00,
}
